title: run-j1j2
opt: adam # adam or minsr
dh: 10 # hidden dimension
N: 6 # linear lattice size (NxN sites)
batches: 2 # Calculation can be broken down into batches to avoid memory blow up
samples_per_batch: 50 # number of samples per batch for energy calculation
numsamples_check: 2000 # numsamples at each checkpoint
numsamples_final: 20000 # numsamples to evaluate energy after final step
lr: 6e-2 # learning rate
m: 0.2 # momentum for SGD / minSR
steps: 10000 # Maximum number of steps allows
step_decay: 5000 # inverse decay rate lr = eta / (1 + t / T)
lambda_reg: 2e-5 # starting lambda reg in minSR [irrelevant for Adam]
