title: run-tfim
opt: minsr # adam or minsr
dh: 32 # hidden dimension
N: 200 # number of spins in 1D chain
batches: 2 # Calculation can be broken down into batches to avoid memory blow up
samples_per_batch: 50 # number of samples per batch for energy calculation
numsamples_check: 3000 # numsamples at each checkpoint
numsamples_final: 30000 # numsamples to evaluate energy after final step
lr: 5e-4 # learning rate
m: 0.7 # momentum for SGD / minSR
steps: 10000 # Maximum number of steps
step_decay: 10000 # inverse decay rate lr = eta / (1 + t / T)
lambda_reg: 2e-3 # starting lambda reg in minSR [irrelevant for Adam]
